AutoVerleih/Models/Verleih.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AutoVerleih.Models
{
    public class Verleih
    {
        [Key]
        [ReadOnly(true)]
        public int ID { get; set; }
        [Required(ErrorMessage = "KundenId fehlt")]
        public int KundenId { get; set; }
        [Required(ErrorMessage = "AutoId fehlt")]
        public int AutoId { get; set; }
        [Required(ErrorMessage = "Ausleihdatum fehlt")]
        public DateTime DT_Von { get; set; }
        public DateTime? DT_Bis { get; set; }
        public DateTime? DT_Rueckgabe { get; set; }
        public int KM_gefahren { get; set; }

        [NotMapped]
        public List<SelectListItem> SelectAutos { get; set; }
    }
}

AutoVerleih/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutoVerleih.Data;
using AutoVerleih.Models;
using System.Collections;
using AutoVerleih.ViewModels;
using AutoVerleih.Filter;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;

namespace AutoVerleih.Controllers
{
    public class CalendarController : Controller
    {

        List<Autos> au = new List<Autos>();
        List<Kunden> ku = new List<Kunden>();
        List<Verleih> vl = new List<Verleih>();

        private readonly DBProjectContext _context;
        private readonly ILogger<HomeController> _logger;

        public CalendarController(DBProjectContext context, ILogger<HomeController> logger)
        {
            _context = context;
            _logger = logger;
        }

        public async Task<IActionResult> Index(string DT_From, bool IsOnlyShowRentCars)
        {
            if (Request.QueryString.HasValue)
            {
                DefaultFilter.DT_From = Convert.ToDateTime(DT_From);
                DefaultFilter.IsOnlyShowRentCars = IsOnlyShowRentCars;
            }
            if (DefaultFilter.IsOnlyShowRentCars)
            {
                vl = await _context.Verleih.Where(a => a.DT_Von >= DefaultFilter.DT_From && a.DT_Rueckgabe == null).ToListAsync();
            }
            else
            {
                vl = await _context.Verleih.Where(a => a.DT_Von >= DefaultFilter.DT_From).ToListAsync();
            }
            au = await _context.Autos.ToListAsync();
            ku = await _context.Kunde.ToListAsync();
            ViewBag.AutosVerliehen = vl.Where(a => a.DT_Rueckgabe == null).Count();

            IEnumerable verleihView = from v in vl
                                      join kui in ku on v.KundenId equals kui.KundenId
                                      join aui in au on v.AutoId equals aui.AutoId
                                      select new VerleihVW { Verleih = v, Kunden = kui, Autos = aui };
            return View(verleihView);
        }
    }
}

AutoVerleih/Controllers/VerleihController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutoVerleih.Data;
using AutoVerleih.Models;
using System.Collections;
using AutoVerleih.ViewModels;
using AutoVerleih.Filter;
using Microsoft.AspNetCore.Authorization;

namespace AutoVerleih.Controllers
{
    [Authorize]
    public class VerleihController : Controller
    {
        List<Autos> au = new List<Autos>();
        List<Kunden> ku = new List<Kunden>();
        List<Verleih> vl = new List<Verleih>();

        private readonly DBProjectContext _context;

        public VerleihController(DBProjectContext context)
        {
            _context = context;
        }

        // GET: Verleih
        public async Task<IActionResult> Index(string DT_From, bool IsOnlyShowRentCars)
        {
            if (Request.QueryString.HasValue)
            {
                DefaultFilter.DT_From = Convert.ToDateTime(DT_From);
                DefaultFilter.IsOnlyShowRentCars = IsOnlyShowRentCars;
            }
            if (DefaultFilter.IsOnlyShowRentCars)
            {
                vl = await _context.Verleih.Where(a => a.DT_Von >= DefaultFilter.DT_From && a.DT_Rueckgabe == null).ToListAsync();
            }
            else
            {
                vl = await _context.Verleih.Where(a => a.DT_Von >= DefaultFilter.DT_From).ToListAsync();
            }
            au = await _context.Autos.ToListAsync();
            ku = await _context.Kunde.ToListAsync();
            ViewBag.AutosVerliehen = vl.Where(a => a.DT_Rueckgabe == null).Count();

            IEnumerable verleihView = from v in vl
                                      join kui in ku on v.KundenId equals kui.KundenId
                                      join aui in au on v.AutoId equals aui.AutoId   
                                      select new VerleihVW { Verleih = v, Kunden = kui, Autos = aui };
            return View(verleihView);
        }

        // GET: Verleih/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var verleih = await _context.Verleih.FirstOrDefaultAsync(m => m.ID == id);
            if (verleih == null)
            {
                return NotFound();
            }

            return View(verleih);
        }

        // GET: Verleih/Create
        public async Task<IActionResult> Create(int KundenNr)
        {
            var verleih = new Verleih();
            verleih.KundenId = KundenNr;
            verleih.DT_Von = DateTime.Today;
            
            ViewBag.KundenNr = verleih.KundenId;
            verleih.SelectAutos = await CreateSelList();

            return View(verleih);
        }

        // POST: Verleih/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,KundenId,AutoId,DT_Von,DT_Bis,DT_Rueckgabe,KM_gefahren")] Verleih verleih)
        {
            if (verleih.AutoId == 0 )
            {
                ViewBag.ErrorMessage = "Es wurde keine Auto ausgewählt, bitte auswählen!";
            }
            else if (ModelState.IsValid)
            {
                _context.Add(verleih);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.KundenNr = verleih.KundenId;
            verleih.SelectAutos = await CreateSelList();

            return View(verleih);
        }

        // GET: Verleih/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var verleih = await _context.Verleih.FindAsync(id);
            if (verleih == null)
            {
                return NotFound();
            }
            return View(verleih);
        }

        // POST: Verleih/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,KundenId,AutoId,DT_Von,DT_Bis,DT_Rueckgabe,KM_gefahren")] Verleih verleih)
        {
            if (id != verleih.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(verleih);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VerleihExists(verleih.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(verleih);
        }

        // GET: Verleih/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var verleih = await _context.Verleih
                .FirstOrDefaultAsync(m => m.ID == id);
            if (verleih == null)
            {
                return NotFound();
            }

            return View(verleih);
        }

        // POST: Verleih/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var verleih = await _context.Verleih.FindAsync(id);
            _context.Verleih.Remove(verleih);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VerleihExists(int id)
        {
            return _context.Verleih.Any(e => e.ID == id);
        }

        private async Task<List<SelectListItem>> CreateSelList()
        {
            au = await _context.Autos.ToListAsync();
            List<SelectListItem> autoList = new List<SelectListItem>();
            autoList.AddRange(au.Select(a => new SelectListItem() { Value = a.AutoId.ToString(), Text = a.AuswahlListe }).ToList());

            return autoList;
        }

        public async Task<IActionResult> Calendar(int? id)
        {
            /*
                        if (id == null)
                        {
                            return NotFound();
                        }

                        var verleih = await _context.Verleih
                            .FirstOrDefaultAsync(m => m.ID == id);
                        if (verleih == null)
                        {
                            return NotFound();
                        }
            */

            var verleih = await _context.Verleih.ToListAsync();
            return View(verleih);
        }


    }
}

AutoVerleih/Views/Verleih/Calendar.cshtml
@model IEnumerable<AutoVerleih.Models.Verleih>
@using AutoVerleih.Filter

@{
    ViewData["Title"] = "Übersicht Auto-Verleih";
}

<h1>@ViewData["Title"]  - derzeit verliehen :  @ViewBag.AutosVerliehen</h1>

@if (@ViewBag.kundenNr != null)
{
    <p>
        <a asp-action="Create" asp-route-kundenNr="@ViewBag.kundenNr">Neuanlage Verleih für Kunde @ViewBag.KundenNr</a>
    </p>
}

@using (Html.BeginForm("Index", "Verleih", FormMethod.Get))
{
    <nav class="float-left">
        <div>
            <label name="VLstatus"> </label>
            Nur verliehen Autos anzeigen : @Html.CheckBox("IsOnlyShowRentCars", @DefaultFilter.IsOnlyShowRentCars)
            AB Leihdatum : @Html.TextBox("DT_From", @DefaultFilter.DT_From)
            <input class="btn btn-sm btn-success" type="submit" value="search" name="button" style="margin-bottom: 5px;" />
        </div>
    </nav>
}

<body>
    <p> Hallo Kalender</p>
    <div id='calendar'></div>
    <p>Test</p>
</body>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(document).ready(function () {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                headerToolbar: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth'
                },
                initialDate: '2020-09-12',
                navLinks: true, // can click day/week names to navigate views
                businessHours: true, // display business hours
                editable: true,
                selectable: true,
                events: [
                    {
                        title: 'Business Lunch',
                        start: '2020-09-03T13:00:00',
                        constraint: 'businessHours'
                    },
                    {
                        title: 'Meeting',
                        start: '2020-09-13T11:00:00',
                        constraint: 'availableForMeeting', // defined below
                        color: '#257e4a'
                    },
                    {
                        title: 'Conference',
                        start: '2020-09-18',
                        end: '2020-09-20'
                    },
                    {
                        title: 'Party',
                        start: '2020-09-29T20:00:00'
                    },

                    // areas where "Meeting" must be dropped
                    {
                        groupId: 'availableForMeeting',
                        start: '2020-09-11T10:00:00',
                        end: '2020-09-11T16:00:00',
                        display: 'background'
                    },
                    {
                        groupId: 'availableForMeeting',
                        start: '2020-09-13T10:00:00',
                        end: '2020-09-13T16:00:00',
                        display: 'background'
                    },

                    // red areas where no events can be dropped
                    {
                        start: '2020-09-24',
                        end: '2020-09-28',
                        overlap: false,
                        display: 'background',
                        color: '#ff9f89'
                    },
                    {
                        start: '2020-09-06',
                        end: '2020-09-08',
                        overlap: false,
                        display: 'background',
                        color: '#ff9f89'
                    }
                ]
            });
            alert("ich bins" + calendarEl + calendar);    
        });
    </script>
}




    <!--
        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth';
                alert("From Kalender");
            });
            calendar.render();
        });
    -->

AutoVerleih/Views/Verleih/Create.cshtml
@model AutoVerleih.Models.Verleih

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Verleih für Kunde @ViewBag.KundenNr </h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="KundenId" class="control-label"></label>
                <input readonly="readonly" asp-for="KundenId" class="form-control" value=@ViewBag.KundenNr />
                <span asp-validation-for="KundenId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AutoId" class="control-label"></label>
                    <select asp-for="AutoId" class="form-control" asp-items="Model.SelectAutos">
                        <option selected>---Select Employee---</option>
                    </select>
                <span asp-validation-for="AutoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DT_Von" class="control-label"></label>
                <input asp-for="DT_Von" class="form-control" />
                <span asp-validation-for="DT_Von" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DT_Bis" class="control-label"></label>
                <input asp-for="DT_Bis" class="form-control" />
                <span asp-validation-for="DT_Bis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DT_Rueckgabe" class="control-label"></label>
                <input asp-for="DT_Rueckgabe" class="form-control" />
                <span asp-validation-for="DT_Rueckgabe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <h4 class="bg-danger">@ViewBag.ErrorMessage </h4>
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AutoVerleih/Views/Verleih/Delete.cshtml
@model AutoVerleih.Models.Verleih

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Verleih</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KundenId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KundenId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AutoId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AutoId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DT_Von)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DT_Von)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DT_Bis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DT_Bis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DT_Rueckgabe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DT_Rueckgabe)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AutoVerleih/Views/Verleih/Details.cshtml
@model AutoVerleih.Models.Verleih

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Verleih</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KundenId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KundenId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AutoId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AutoId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DT_Von)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DT_Von)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DT_Bis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DT_Bis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DT_Rueckgabe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DT_Rueckgabe)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AutoVerleih/Views/Verleih/Edit.cshtml
@model AutoVerleih.Models.Verleih

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Verleih</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="KundenId" class="control-label"></label>
                <input readonly="readonly" asp-for="KundenId" class="form-control" />
                <span asp-validation-for="KundenId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AutoId" class="control-label"></label>
                <input readonly="readonly" asp-for="AutoId" class="form-control" />
                <span asp-validation-for="AutoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DT_Von" class="control-label"></label>
                <input asp-for="DT_Von" class="form-control" />
                <span asp-validation-for="DT_Von" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DT_Bis" class="control-label"></label>
                <input asp-for="DT_Bis" class="form-control" />
                <span asp-validation-for="DT_Bis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DT_Rueckgabe" class="control-label"></label>
                <input asp-for="DT_Rueckgabe" class="form-control" />
                <span asp-validation-for="DT_Rueckgabe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KM_gefahren" class="control-label"></label>
                <input asp-for="KM_gefahren" class="form-control" />
                <span asp-validation-for="KM_gefahren" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AutoVerleih/Views/Verleih/Index.cshtml
@model IEnumerable<AutoVerleih.ViewModels.VerleihVW>
@using AutoVerleih.Filter

@{
    ViewData["Title"] = "Übersicht Auto-Verleih";
}

<h1>@ViewData["Title"]  - derzeit verliehen :  @ViewBag.AutosVerliehen</h1>

@if (@ViewBag.kundenNr != null)
{
    <p>
        <a asp-action="Create" asp-route-kundenNr="@ViewBag.kundenNr">Neuanlage Verleih für Kunde @ViewBag.KundenNr</a>
    </p>
}

<!--
<label for="txtTo" class="control-label">Datum Von</label>
<input id="txtTo" type="datetime" asp-format="{0:yyyy-MM-dd}" class="form-control" value="@DefaultFilter.DT_To" name="DT_To" />
-->


@using (Html.BeginForm("Index", "Verleih", FormMethod.Get))
{
    <nav class="float-left">
        <div>
            <label name="VLstatus"> </label>
            Nur verliehen Autos anzeigen : @Html.CheckBox("IsOnlyShowRentCars", @DefaultFilter.IsOnlyShowRentCars)
            AB Leihdatum : @Html.TextBox("DT_From", @DefaultFilter.DT_From)
            <input class="btn btn-sm btn-success" type="submit" value="search" name="button" style="margin-bottom: 5px;" />
        </div>
    </nav>
}


<table class="table table-bordered table-hover">
    <thead id="tableHeader">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Verleih.KundenId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Kunden.Name)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Verleih.AutoId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autos.Bild)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autos.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Verleih.DT_Von)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Verleih.DT_Bis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Verleih.DT_Rueckgabe)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Verleih.KM_gefahren)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Verleih.KundenId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Kunden.Name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Verleih.AutoId)
                </td>
                <td>
                    <img src="/images/@item.Autos.Bild" class="detailImage" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Autos.Type)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Verleih.DT_Von)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Verleih.DT_Bis)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Verleih.DT_Rueckgabe)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Verleih.KM_gefahren)
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.Verleih.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Verleih.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Verleih.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>