AutoVerleih/Controllers/AutosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutoVerleih.Data;
using AutoVerleih.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;

namespace AutoVerleih.Controllers
{
    [Authorize]
    public class AutosController : Controller
    {
        private readonly DBProjectContext _context;

        public AutosController(DBProjectContext context)
        {
            _context = context;
        }
      
        // GET: Autos
        public async Task<IActionResult> Index(string currentFilter, string searchString)
        {

            var autos = new List<Autos>();
            if (!String.IsNullOrEmpty(searchString))
            {
                autos = await _context.Autos.Where(s => s.Type.Contains(searchString)).ToListAsync();
            }
            else
            {
                autos = await _context.Autos.ToListAsync();
            }
            foreach(var auto in autos)
            {
                var xx = _context.Verleih.Where(a => a.AutoId == auto.AutoId).Select(b => b.KM_gefahren).Sum();
                auto.KM_gesamt = auto.KM_gesamt + xx;
            }
            return View(autos.ToList());
        }

        // GET: Autos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autos = await _context.Autos
                .FirstOrDefaultAsync(m => m.AutoId == id);
            if (autos == null)
            {
                return NotFound();
            }

            return View(autos);
        }

        // GET: Autos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Autos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AutoId,Marke,Type,Farbe,MietPreis_HH,MietPreis_TG,MietPreis_WE,vermietet,Bild")] Autos autos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(autos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(autos);
        }

        // GET: Autos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autos = await _context.Autos.FindAsync(id);
            if (autos == null)
            {
                return NotFound();
            }
            return View(autos);
        }

        // POST: Autos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AutoId,Marke,Type,Farbe,MietPreis_HH,MietPreis_TG,MietPreis_WE,vermietet,Bild")] Autos autos)
        {
            if (id != autos.AutoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(autos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AutosExists(autos.AutoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(autos);
        }

        // GET: Autos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autos = await _context.Autos.FirstOrDefaultAsync(m => m.AutoId == id);
            if (autos == null)
            {
                return NotFound();
            }

            var verleih = await _context.Verleih.FirstOrDefaultAsync(r => r.AutoId == id);
            if (verleih != null)
            {
                ViewBag.ErrorMessage = "Löschen nicht mgölich, für dieses Auto sind im Verleih Datnsätze vorhanden!";
            }

            return View(autos);
        }

        // POST: Autos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var autos = await _context.Autos.FindAsync(id);
            _context.Autos.Remove(autos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AutosExists(int id)
        {
            return _context.Autos.Any(e => e.AutoId == id);
        }
    }
}

AutoVerleih/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutoVerleih.Data;
using AutoVerleih.Models;
using System.Collections;
using AutoVerleih.ViewModels;
using AutoVerleih.Filter;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;

namespace AutoVerleih.Controllers
{
    public class CalendarController : Controller
    {

        List<Autos> au = new List<Autos>();
        List<Kunden> ku = new List<Kunden>();
        List<Verleih> vl = new List<Verleih>();

        private readonly DBProjectContext _context;
        private readonly ILogger<HomeController> _logger;

        public CalendarController(DBProjectContext context, ILogger<HomeController> logger)
        {
            _context = context;
            _logger = logger;
        }

        public async Task<IActionResult> Index(string DT_From, bool IsOnlyShowRentCars)
        {
            if (Request.QueryString.HasValue)
            {
                DefaultFilter.DT_From = Convert.ToDateTime(DT_From);
                DefaultFilter.IsOnlyShowRentCars = IsOnlyShowRentCars;
            }
            if (DefaultFilter.IsOnlyShowRentCars)
            {
                vl = await _context.Verleih.Where(a => a.DT_Von >= DefaultFilter.DT_From && a.DT_Rueckgabe == null).ToListAsync();
            }
            else
            {
                vl = await _context.Verleih.Where(a => a.DT_Von >= DefaultFilter.DT_From).ToListAsync();
            }
            au = await _context.Autos.ToListAsync();
            ku = await _context.Kunde.ToListAsync();
            ViewBag.AutosVerliehen = vl.Where(a => a.DT_Rueckgabe == null).Count();

            IEnumerable verleihView = from v in vl
                                      join kui in ku on v.KundenId equals kui.KundenId
                                      join aui in au on v.AutoId equals aui.AutoId
                                      select new VerleihVW { Verleih = v, Kunden = kui, Autos = aui };
            return View(verleihView);
        }
    }
}

AutoVerleih/Controllers/KundenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AutoVerleih.Models;
using X.PagedList;
using AutoVerleih.Data;
using AutoVerleih.Filter;
using Microsoft.CodeAnalysis;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace AutoVerleih.Controllers
{
    [Authorize]
    public class KundenController : Controller
    {
        private readonly DBProjectContext _context;
        
        public KundenController(DBProjectContext context)
        {
            _context = context;
        }
         
        // GET: Kunden
        public async Task<IActionResult> Index(string button, string currentFilter, string searchString, string currentScreen, int? page, int anzLine)
        {
            if (anzLine == 0) anzLine = DefaultFilter.AnzLine;

            if (!HttpContext.Request.Cookies.ContainsKey("first_request"))
            {

                HttpContext.Response.Cookies.Append("first_request", DateTime.Now.ToString());
//                return Content("Welcome, new visitor!");
            }
            else
            {
                DateTime firstRequest = DateTime.Parse(HttpContext.Request.Cookies["first_request"]);
            }

            if (!String.IsNullOrEmpty(currentFilter) && String.IsNullOrEmpty(searchString)) searchString = currentFilter;
            IEnumerable<Kunden> kunden = Enumerable.Empty<Kunden>();

            if (!String.IsNullOrEmpty(searchString))
            {
                kunden = await _context.Kunde.Where(s => s.Name.Contains(searchString)).ToListAsync();       
            }
            else
            {
                searchString = currentFilter;
                kunden = await _context.Kunde.OrderByDescending(s => s.KundenId).Take(10).ToListAsync();
            }

            //            var xx = kunden.FirstOrDefault(a => a.Verleihs.Count > 0);

            ViewBag.CurrentFilter = searchString;
            ViewBag.AnzLine = anzLine;

            int pageSize = anzLine;
            int pageNumber = (page ?? 1);
            return View(kunden.ToPagedList(pageNumber, pageSize));
        }

        // GET: Kunden/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kunde = await _context.Kunde
                .FirstOrDefaultAsync(m => m.KundenId == id);
            if (kunde == null)
            {
                return NotFound();
            }

            return View(kunde);
        }

        // GET: Kunden/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Kunden/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("KundenId,Name,Plz,Ort,Strasse")] Kunden kunde)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kunde);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(kunde);
        }

        // GET: Kunden/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kunde = await _context.Kunde.FindAsync(id);
            if (kunde == null)
            {
                return NotFound();
            }
            return View(kunde);
        }

        // POST: Kunden/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("KundenId,Name,Plz,Ort,Strasse")] Kunden kunde)
        {
            var xx = DefaultFilter.DT_From;
            
            if (id != kunde.KundenId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kunde);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KundeExists(kunde.KundenId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(kunde);
        }

        // GET: Kunden/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var kunde = await _context.Kunde.FirstOrDefaultAsync(m => m.KundenId == id);
            if (kunde == null)
            {
                return NotFound();
            }

            var verleih = await _context.Verleih.FirstOrDefaultAsync(r => r.KundenId == id);
            if (verleih != null)
            {
                ViewBag.ErrorMessage = "Löschen nicht möglich, für diesen Kunden sind im Verleih Datnsätze vorhanden!";
            }

            return View(kunde);
        }

        // POST: Kunden/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kunde = await _context.Kunde.FindAsync(id);
            _context.Kunde.Remove(kunde);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KundeExists(int id)
        {
            return _context.Kunde.Any(e => e.KundenId == id);
        }
    }
}

AutoVerleih/Views/Shared/_Layout.cshtml
@using AutoVerleih.Filter
<!DOCTYPE html>
<html lang="de-at">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoVerleih</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AutoVerleih</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 navbar-brand">
                        <li class="nav-item btn-outline-light">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kunden" asp-action="Index">KundenListe</a>
                        </li>
                        <li class="nav-item btn-outline-light">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Autos" asp-action="Index">AutoListe</a>
                        </li>
                        <li class="nav-item btn-outline-light">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Verleih" asp-action="Index">Verleih</a>
                        </li>
                        <li class="nav-item btn-outline-light">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calendar" asp-action="Index">Kalender</a>
                        </li>

                    </ul>

                    <ul class="navbar-nav flex-grow-1 navbar-brand float-right">
                        <li class="nav-item">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link text-dark text-info" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark text-info" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                            }
                        <li class="nav-item">
                    </ul>
                </div>
            </div>
        </nav>
        <div>
            <!--
                    <form>
                        <label for="From" Text="Hallo">Datum Von:</label>
                        <input type="datetime" value="@DefaultFilter.DT_From" name="DT_From" id="From" />
                        <input class="btn btn-sm btn-outline-success" type="submit" value="Suche" style="margin-bottom: 5px;" />
                    </form>
            -->
        </div>
    </header>

    <div class="container" id="ausgabeView">
        <main role="main" class="pb-4">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>